import {
  DEFAULT_LLM_SYSTEM_PROMPT,
  DEFAULT_LLM_USER_PROMPT,
  type LlmSettings,
} from "./llm";
import type {
  ConvertSourceKind,
  ConvertSourceSettings,
  ExportSkipSourceSettings,
  LocaleCode,
  LocaleFallbacks,
  LlmReferenceMode,
  SourceKind,
} from "./types";
import { DEFAULT_CHINESE_LOCALE_FALLBACKS, DEFAULT_CONVERT_SOURCE_SETTINGS, DEFAULT_EXPORT_SKIP_SOURCES } from "./types";
import { isChineseLocale, normalizeLocaleCode, uniqueLocaleCodes } from "./locales";

export const DEPLOYMENT_CONFIG_FILENAME = "app-config.json";
export const OFFICIAL_OPENAI_API_BASE_URL = "https://api.openai.com/v1";

export const SOURCE_LABEL_ORDER: SourceKind[] = ["vanilla", "jar", "resourcePack", "converted", "llm", "manual", "fallback", "missing"];
export const SOURCE_TRANSLATE_TARGET_ORDER: SourceKind[] = ["vanilla", "jar", "resourcePack", "converted", "llm", "manual", "fallback", "missing"];
export const CONVERT_SOURCE_ORDER: ConvertSourceKind[] = ["manual", "llm", "resourcePack", "jar", "vanilla"];
export const DEFAULT_FALLBACK_LOCALE = "en_us";
export const LLM_REFERENCE_MODES: LlmReferenceMode[] = ["en_us", "fallback", "all"];

export interface SourceLabelStyle {
  label: string;
  background: string;
  text: string;
  stripe: string;
}

export type SourceLabelSettings = Record<SourceKind, SourceLabelStyle>;

export interface AppSettings {
  projectMode: "resourcePack";
  sourcePackMode: "prune" | "keep";
  inspectorWidth: number;
  packFormat: number;
  description: string;
  llmBatchSize: number;
  llmConcurrency: number;
  llmReferenceMode: LlmReferenceMode;
  warnFormattingCodeMismatch: boolean;
  targetLocales: LocaleCode[];
  fallbackChains: LocaleFallbacks;
  translateSourceTargets: Record<SourceKind, boolean>;
  convertSources: ConvertSourceSettings;
  exportSkipSources: ExportSkipSourceSettings;
}

export type PersistedLlmSettings = Omit<LlmSettings, "apiKey">;

export interface DeploymentDefaults {
  settings: AppSettings;
  llmSettings: LlmSettings;
  sourceLabels: SourceLabelSettings;
}

type ConfigFetcher = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;

const DEFAULT_SOURCE_LABELS: SourceLabelSettings = {
  vanilla: { label: "Vanilla", background: "#f0f4dc", text: "#566422", stripe: "#9aac45" },
  jar: { label: "Jar", background: "#e6edf7", text: "#315b8c", stripe: "#6c8fba" },
  resourcePack: { label: "Resource pack", background: "#ecf7e7", text: "#436f2d", stripe: "#75a857" },
  converted: { label: "Converted", background: "#e0f4ef", text: "#1d6c5b", stripe: "#2f9a83" },
  llm: { label: "LLM", background: "#f3eafd", text: "#6c3a95", stripe: "#9a69bf" },
  manual: { label: "Manual", background: "#fff0d7", text: "#8a5a13", stripe: "#c28a2c" },
  fallback: { label: "Fallback", background: "#f2eeee", text: "#7b4a4a", stripe: "#aa7474" },
  missing: { label: "Missing", background: "#eceff3", text: "#5d6875", stripe: "#8d98a5" },
};

export function createDefaultAppSettings(): AppSettings {
  return {
    projectMode: "resourcePack",
    sourcePackMode: "prune",
    inspectorWidth: 430,
    packFormat: 34,
    description: "Generated by Minecraft Mods Localizer",
    llmBatchSize: 40,
    llmConcurrency: 3,
    llmReferenceMode: "en_us",
    warnFormattingCodeMismatch: false,
    targetLocales: [],
    fallbackChains: {},
    convertSources: { ...DEFAULT_CONVERT_SOURCE_SETTINGS },
    exportSkipSources: { ...DEFAULT_EXPORT_SKIP_SOURCES },
    translateSourceTargets: {
      vanilla: false,
      jar: false,
      resourcePack: false,
      converted: false,
      llm: false,
      manual: false,
      fallback: true,
      missing: false,
    },
  };
}

export function createDefaultLlmSettings(): LlmSettings {
  return {
    baseUrl: OFFICIAL_OPENAI_API_BASE_URL,
    apiKey: "",
    model: "gpt-5.4-mini",
    systemPrompt: DEFAULT_LLM_SYSTEM_PROMPT,
    userPrompt: DEFAULT_LLM_USER_PROMPT,
    debugMode: false,
    debugDelayMs: 120,
  };
}

export function createDefaultSourceLabels(): SourceLabelSettings {
  return cloneSourceLabels(DEFAULT_SOURCE_LABELS);
}

export function createDefaultDeploymentDefaults(): DeploymentDefaults {
  return {
    settings: createDefaultAppSettings(),
    llmSettings: createDefaultLlmSettings(),
    sourceLabels: createDefaultSourceLabels(),
  };
}

export function normalizeDeploymentConfig(raw: unknown, base: DeploymentDefaults = createDefaultDeploymentDefaults()): DeploymentDefaults {
  if (!isRecord(raw)) {
    return cloneDeploymentDefaults(base);
  }

  return {
    settings: normalizeAppSettings(raw.app, base.settings),
    llmSettings: normalizeOpenAiApiSettings(raw.openai_api, base.llmSettings),
    sourceLabels: normalizeSourceLabels(raw.sourceLabels, base.sourceLabels),
  };
}

export async function loadDeploymentConfig(fetcher?: ConfigFetcher, url = deploymentConfigUrl()): Promise<DeploymentDefaults> {
  try {
    const request = fetcher ?? globalThis.fetch.bind(globalThis);
    const response = await request(url, { cache: "no-store" });
    if (!response.ok) {
      return createDefaultDeploymentDefaults();
    }
    return normalizeDeploymentConfig(await response.json());
  } catch {
    return createDefaultDeploymentDefaults();
  }
}

export function deploymentConfigUrl(): string {
  const base =
    typeof document !== "undefined"
      ? document.baseURI
      : typeof location !== "undefined"
        ? location.href
        : "http://localhost/";
  return new URL(DEPLOYMENT_CONFIG_FILENAME, base).toString();
}

export function mergeAppSettings(saved: AppSettings | undefined, defaults: AppSettings = createDefaultAppSettings()): AppSettings {
  return normalizeAppSettings(saved, defaults);
}

export function mergeLlmSettings(defaults: LlmSettings, saved: PersistedLlmSettings | undefined): LlmSettings {
  const next = cloneLlmSettings(defaults);
  if (!isRecord(saved)) {
    return next;
  }

  applyString(saved.baseUrl, (value) => {
    next.baseUrl = value;
  });
  applyString(saved.model, (value) => {
    next.model = value;
  });
  applyString(saved.systemPrompt, (value) => {
    next.systemPrompt = value;
  });
  applyString(saved.userPrompt, (value) => {
    next.userPrompt = value;
  });
  if (typeof saved.debugMode === "boolean") {
    next.debugMode = saved.debugMode;
  }
  applyNumber(saved.debugDelayMs, (value) => {
    next.debugDelayMs = clamp(Math.round(value), 0, 5000);
  });

  return next;
}

export function normalizeFallbackChain(locale: LocaleCode, chain: readonly unknown[]): string[] {
  return uniqueLocaleCodes([...chain, DEFAULT_FALLBACK_LOCALE]).filter((item) => item !== locale);
}

export function defaultFallbackChainForLocale(locale: LocaleCode): string[] {
  const normalized = normalizeLocaleCode(locale);
  return isChineseLocale(normalized) ? [...DEFAULT_CHINESE_LOCALE_FALLBACKS[normalized]] : [];
}

export function clamp(value: number, minimum: number, maximum: number): number {
  return Math.min(Math.max(value, minimum), maximum);
}

function normalizeAppSettings(raw: unknown, base: AppSettings): AppSettings {
  const next = cloneAppSettings(base);
  if (!isRecord(raw)) {
    return next;
  }

  if (raw.projectMode === "resourcePack") {
    next.projectMode = raw.projectMode;
  }
  if (raw.sourcePackMode === "prune" || raw.sourcePackMode === "keep") {
    next.sourcePackMode = raw.sourcePackMode;
  }
  applyNumber(raw.inspectorWidth, (value) => {
    next.inspectorWidth = clamp(Math.round(value), 320, 620);
  });
  applyNumber(raw.packFormat, (value) => {
    next.packFormat = Math.max(1, Math.round(value));
  });
  applyString(raw.description, (value) => {
    next.description = value;
  });
  applyNumber(raw.llmBatchSize, (value) => {
    next.llmBatchSize = clamp(Math.round(value), 1, 200);
  });
  applyNumber(raw.llmConcurrency, (value) => {
    next.llmConcurrency = clamp(Math.round(value), 1, 12);
  });
  if (isLlmReferenceMode(raw.llmReferenceMode)) {
    next.llmReferenceMode = raw.llmReferenceMode;
  }
  if (typeof raw.warnFormattingCodeMismatch === "boolean") {
    next.warnFormattingCodeMismatch = raw.warnFormattingCodeMismatch;
  }

  if (Array.isArray(raw.targetLocales)) {
    next.targetLocales = uniqueLocaleCodes(raw.targetLocales);
  }
  if (isRecord(raw.fallbackChains)) {
    next.fallbackChains = normalizeFallbackChains(raw.fallbackChains, next.targetLocales, next.fallbackChains);
  } else {
    next.fallbackChains = normalizeFallbackChains(next.fallbackChains, next.targetLocales);
  }

  next.convertSources = mergeBooleanRecord(next.convertSources, raw.convertSources, CONVERT_SOURCE_ORDER);
  next.exportSkipSources = mergeBooleanRecord(next.exportSkipSources, raw.exportSkipSources, SOURCE_LABEL_ORDER);
  next.translateSourceTargets = mergeBooleanRecord(next.translateSourceTargets, raw.translateSourceTargets, SOURCE_LABEL_ORDER);

  return next;
}

function normalizeOpenAiApiSettings(raw: unknown, base: LlmSettings): LlmSettings {
  const next = cloneLlmSettings(base);
  if (!isRecord(raw)) {
    return next;
  }

  applyString(raw.base_url ?? raw.baseUrl, (value) => {
    next.baseUrl = value;
  });
  applyString(raw.model, (value) => {
    next.model = value;
  });
  applyString(raw.system_prompt ?? raw.systemPrompt, (value) => {
    next.systemPrompt = value;
  });
  applyString(raw.user_prompt ?? raw.userPrompt, (value) => {
    next.userPrompt = value;
  });
  const debugMode = raw.debug_mode ?? raw.debugMode;
  if (typeof debugMode === "boolean") {
    next.debugMode = debugMode;
  }
  applyNumber(raw.debug_delay_ms ?? raw.debugDelayMs, (value) => {
    next.debugDelayMs = clamp(Math.round(value), 0, 5000);
  });

  return next;
}

function normalizeSourceLabels(raw: unknown, base: SourceLabelSettings): SourceLabelSettings {
  const next = cloneSourceLabels(base);
  if (!isRecord(raw)) {
    return next;
  }

  for (const source of SOURCE_LABEL_ORDER) {
    const sourceConfig = raw[source];
    if (!isRecord(sourceConfig)) {
      continue;
    }
    applyString(sourceConfig.label, (value) => {
      next[source].label = value;
    });
    applyColor(sourceConfig.background, (value) => {
      next[source].background = value;
    });
    applyColor(sourceConfig.text, (value) => {
      next[source].text = value;
    });
    applyColor(sourceConfig.stripe, (value) => {
      next[source].stripe = value;
    });
  }

  return next;
}

function cloneDeploymentDefaults(defaults: DeploymentDefaults): DeploymentDefaults {
  return {
    settings: cloneAppSettings(defaults.settings),
    llmSettings: cloneLlmSettings(defaults.llmSettings),
    sourceLabels: cloneSourceLabels(defaults.sourceLabels),
  };
}

function cloneAppSettings(settings: AppSettings): AppSettings {
  return {
    ...settings,
    targetLocales: [...settings.targetLocales],
    fallbackChains: cloneFallbackChains(settings.fallbackChains),
    translateSourceTargets: { ...settings.translateSourceTargets },
    convertSources: { ...settings.convertSources },
    exportSkipSources: { ...settings.exportSkipSources },
  };
}

function normalizeFallbackChains(raw: unknown, targetLocales: readonly LocaleCode[], base: LocaleFallbacks = {}): LocaleFallbacks {
  const source = isRecord(raw) ? raw : {};
  const next: LocaleFallbacks = {};
  for (const locale of targetLocales) {
    const rawChain = Array.isArray(source[locale])
      ? source[locale]
      : Array.isArray(base[locale])
        ? base[locale]
        : defaultFallbackChainForLocale(locale);
    next[locale] = normalizeFallbackChain(locale, rawChain);
  }
  return next;
}

function cloneFallbackChains(fallbackChains: LocaleFallbacks): LocaleFallbacks {
  return Object.fromEntries(Object.entries(fallbackChains).map(([locale, chain]) => [locale, [...chain]]));
}

function cloneLlmSettings(settings: LlmSettings): LlmSettings {
  return { ...settings };
}

function cloneSourceLabels(labels: SourceLabelSettings): SourceLabelSettings {
  return Object.fromEntries(SOURCE_LABEL_ORDER.map((source) => [source, { ...labels[source] }])) as SourceLabelSettings;
}

function mergeBooleanRecord<T extends string>(base: Record<T, boolean>, raw: unknown, keys: readonly T[]): Record<T, boolean> {
  const next = { ...base };
  if (!isRecord(raw)) {
    return next;
  }
  for (const key of keys) {
    if (typeof raw[key] === "boolean") {
      next[key] = raw[key];
    }
  }
  return next;
}

function isLlmReferenceMode(value: unknown): value is LlmReferenceMode {
  return typeof value === "string" && (LLM_REFERENCE_MODES as readonly string[]).includes(value);
}

function applyString(value: unknown, setValue: (value: string) => void) {
  if (typeof value !== "string") {
    return;
  }
  const trimmed = value.trim();
  if (trimmed) {
    setValue(trimmed);
  }
}

function applyNumber(value: unknown, setValue: (value: number) => void) {
  const numberValue = typeof value === "number" ? value : typeof value === "string" ? Number(value) : Number.NaN;
  if (Number.isFinite(numberValue)) {
    setValue(numberValue);
  }
}

function applyColor(value: unknown, setValue: (value: string) => void) {
  if (typeof value === "string" && /^#[0-9a-f]{3}(?:[0-9a-f]{3})?$/i.test(value.trim())) {
    setValue(value.trim());
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value && typeof value === "object" && !Array.isArray(value));
}
