import JSZip from "jszip";

import type { CatalogRow, SourceKind, SourcePackScanResult, TargetLocale } from "./types";
import { TARGET_LOCALES } from "./types";

export interface ExportPackOptions {
  packFormat?: number;
  description?: string;
  sourcePacks?: SourcePackScanResult[];
  sourcePackMode?: "prune" | "keep";
  skipSources?: Partial<Record<SourceKind, boolean>>;
}

export async function createResourcePackZip(
  rows: CatalogRow[],
  locales: readonly TargetLocale[] = TARGET_LOCALES,
  options: ExportPackOptions = {},
): Promise<Blob> {
  const zip = new JSZip();
  const packFormat = options.packFormat ?? 34;
  const description = options.description ?? `Generated by Minecraft Mods Localizer\nLocales: ${locales.join(", ")}`;

  zip.file(
    "pack.mcmeta",
    JSON.stringify(
      {
        pack: {
          pack_format: packFormat,
          description,
        },
      },
      null,
      2,
    ) + "\n",
  );

  const output = new Map<string, Map<string, Record<string, string>>>();
  if (options.sourcePackMode === "keep") {
    for (const pack of [...(options.sourcePacks ?? [])].reverse()) {
      for (const [namespace, namespaceLocales] of Object.entries(pack.translations)) {
        for (const locale of locales) {
          const data = namespaceLocales[locale];
          if (!data) {
            continue;
          }
          Object.assign(localeOutput(output, namespace, locale), data);
        }
      }
    }
  }

  const byNamespace = new Map<string, CatalogRow[]>();
  for (const row of rows) {
    byNamespace.set(row.namespace, [...(byNamespace.get(row.namespace) ?? []), row]);
  }

  for (const [namespace, namespaceRows] of [...byNamespace.entries()].sort(([left], [right]) => left.localeCompare(right))) {
    for (const locale of locales) {
      const data = localeOutput(output, namespace, locale);
      for (const row of namespaceRows) {
        if (options.skipSources?.[row.entries[locale].final.source]) {
          continue;
        }
        data[row.key] = row.entries[locale].final.value;
      }
    }
  }

  for (const [namespace, namespaceLocales] of [...output.entries()].sort(([left], [right]) => left.localeCompare(right))) {
    for (const [locale, data] of [...namespaceLocales.entries()].sort(([left], [right]) => left.localeCompare(right))) {
      if (Object.keys(data).length > 0) {
        zip.file(`assets/${namespace}/lang/${locale}.json`, JSON.stringify(sortObject(data), null, 2) + "\n");
      }
    }
  }

  return zip.generateAsync({ type: "blob", compression: "DEFLATE" });
}

function localeOutput(output: Map<string, Map<string, Record<string, string>>>, namespace: string, locale: string): Record<string, string> {
  let namespaceLocales = output.get(namespace);
  if (!namespaceLocales) {
    namespaceLocales = new Map();
    output.set(namespace, namespaceLocales);
  }
  let data = namespaceLocales.get(locale);
  if (!data) {
    data = {};
    namespaceLocales.set(locale, data);
  }
  return data;
}

function sortObject(data: Record<string, string>): Record<string, string> {
  return Object.fromEntries(Object.entries(data).sort(([left], [right]) => left.localeCompare(right)));
}
